### ISSUE TITLE
smb2 is not working after Yasomite upgrade

### ISSUE THREAD

**Issue by bipramohanty** [bchelli/node-smb2#11]
I was able to write file to windows shared drive before Yasomite upgrade but not I am getting following error.I updated node and npm to the latest version but no luck

Error: STATUS_INVALID_PARAMETER (0xC000000D) : An invalid parameter was passed to a service or function.
    at Object.05000000 (/node_modules/smb2/lib/tools/message.js:25:18)
    at Socket.<anonymous> (/node_modules/smb2/lib/tools/smb2-forge.js:72:31)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

**Comment by arcticShadow** [comment]
By Yasomite, do you mean Yosemite?

**Comment by anilpai** [comment]
I am having the same issue as well.. Not sure if it has anything to do with Yosemite OS.

```
Error: STATUS_INVALID_PARAMETER (0xC000000D) : An invalid parameter was passed to a service or function.
    at Object.04000000 (/Users/anilpai/Desktop/filetransfer/node_modules/smb2/lib/tools/message.js:25:18)
    at Socket.<anonymous> (/Users/anilpai/Desktop/filetransfer/node_modules/smb2/lib/tools/smb2-forge.js:72:31)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:529:20)


```

**Comment by fradiocey** [comment]
I also having same issue, I tried to connect with shared folder and want to access the file but give above error message, I tried also using MAC OS and Windows, but the result is same.

Can anyone check my code whether correct or not.

var smb2Client = new SMB2({
  share:'\\\\mymswfs01\\'
, domain:'s*nw*y.c*m'
, username:'Private'
, password:'Private'
});

smb2Client.readFile('180-Public\\BPMS\\Book1.xlsx', function(err, data){
    if(err){
    console.log(err);
	}
});

**Comment by magnusottosson** [comment]
Did anyone solve this? I have the same issue...

**Comment by EricLStevens** [comment]
Did anybody figure this out?

**Comment by magnusottosson** [comment]
I got this one when connecting to a smb path without username/password. I solved it by using node fs lib instead which has support for UNC paths (when anonymous acces is grantes)

**Comment by Ahmedhkad** [comment]
I just found the solution , I made single file server.js and all function worked fine ,
 but when file get long , i spilted it and got error , 
i debugged my code (console.log functions) i found that  smbClient.readdir(currentFolderPath, { stats: true }, (err, files) =>  . is makes the error , and the passed currentFolderPath got changed from   \share\\test    to   \share\test    
yeah its that single symbol    \
