### ISSUE TITLE
Error: Invalid key length

### ISSUE THREAD

**Issue by mithrandirii** [bchelli/node-smb2#16]
after migrating to node.js 6 we get the uncaughtException by using this module.

the stacktrace ...

Error: Invalid key length',
     '    at Error (native)',
     '    at new Cipheriv (crypto.js:184:16)',
     '    at Object.Cipheriv (crypto.js:182:12)',
     '    at makeResponse (/home/mithrandir/dev/node/node_modules/ntlm/lib/ntlm.js:212:22)',
     '    at Object.encodeType3 (/home/mithrandir/dev/node/node_modules/ntlm/lib/ntlm.js:112:13)',
     '    at Object.module.exports.message.generate (/home/mithrandir/dev/node/node_modules/smb2/lib/messages/session_setup_step2.js:20:23)',
     '    at SMB2Forge.request (/home/mithrandir/dev/node/node_modules/smb2/lib/tools/smb2-forge.js:20:24)',
     '    at /home/mithrandir/dev/node/node_modules/smb2/lib/tools/smb2-connection.js:101:12',
     '    at Object.01000000 (/home/mithrandir/dev/node/node_modules/smb2/lib/tools/message.js:20:15)',
     '    at Socket.<anonymous> (/home/mithrandir/dev/node/node_modules/smb2/lib/tools/smb2-forge.js:72:31)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:172:18)',
     '    at Socket.Readable.push (_stream_readable.js:130:10)',
     '    at TCP.onread (net.js:535:20)

with node.js 5.11 it worked fine.

**Comment by mithrandirii** [comment]
i did some deeper inspection to this. it seems to me the bug is related to the ntlm module. the tests of this module fail in nodejs 6 while running successfully with node js 5.11

**Comment by echicken** [comment]
I was having the same problem.  I modified ntlm.js and smbhash.js so that Buffers 'keybuf' and 'z', respectively, were passed to crypto.createCipheriv as the second (key) parameter directly, rather than first converting them to binary strings, and that got it working for me under node.js 6.

This was based on another thread I read (which I can't for the life of me find now) that mentioned a change in the behaviour of crypto.createCipheriv in node.js 6.  The suggestion was that it now expects a Buffer for the 'key' parameter - though I'm not sure that's necessarily true and the docs don't seem to have changed.

I'll have to test my changes with a few versions of node; if they seem backward-compatible, I may do a PR to node-ntlm.  Would certainly like to know if this solves the problem for you too.

**Comment by mithrandirii** [comment]
it worked for me too !
the tests run again in ntlm lib and the smb2 lib work again, THX ;)

**Comment by michaelPf85** [comment]
Hello,
I had the same problem and your fix did the job ! Should we make the PR ?
