### ISSUE TITLE
Error: Invalid key length (crypto.js:190   this._handle.initiv(cipher, toBuf(key), toBuf(iv));)

### ISSUE THREAD

**Issue by m3n1at** [bchelli/node-smb2#18]
Hi there.  
I've got error "Error: Invalid key length" after exectuing code below on Windows 10

var smb2Client = new smb2(config.smb); //valid config.smb
smb2Client.readdir('USB3\\Lang', function (err, Data) {
		    if (err) 
		    	return cb(err);
		    //cb(null,exists ? "it's there" : "it's not there!");
		    console.log(Data);
});
And here is error stack:
crypto.js:190
  this._handle.initiv(cipher, toBuf(key), toBuf(iv));
               ^

Error: Invalid key length
    at Error (native)
    at new Cipheriv (crypto.js:190:16)
    at Object.Cipheriv (crypto.js:188:12)
    at D:\Workspace\Eclipse\BeorgBot\node_modules\ntlm\lib\smbhash.js:47:22
    at Array.forEach (native)
    at lmhashbuf (D:\Workspace\Eclipse\BeorgBot\node_modules\ntlm\lib\smbhash.js:45:20)
    at Object.encodeType3 (D:\Workspace\Eclipse\BeorgBot\node_modules\ntlm\lib\ntlm.js:106:3)
    at Object.module.exports.message.generate (D:\Workspace\Eclipse\BeorgBot\node_modules\smb2\lib\messages\session_setup_step2.js:20:23)
    at SMB2Forge.request (D:\Workspace\Eclipse\BeorgBot\node_modules\smb2\lib\tools\smb2-forge.js:20:24)
    at D:\Workspace\Eclipse\BeorgBot\node_modules\smb2\lib\tools\smb2-connection.js:101:12
    at Object.01000000 (D:\Workspace\Eclipse\BeorgBot\node_modules\smb2\lib\tools\message.js:20:15)
    at Socket.<anonymous> (D:\Workspace\Eclipse\BeorgBot\node_modules\smb2\lib\tools\smb2-forge.js:72:31)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)

**Comment by prabhatkm** [comment]
I'm facing same problem. Did you by any chance find any solution?
