### ISSUE TITLE
STATUS_WRONG_PASSWORD

### ISSUE THREAD

**Issue by mahacoder** [bchelli/node-smb2#19]
I wrote the following code to connect and read a directory.

```
var SMB2 = require('smb2');

var smb2Client = new SMB2({
  share:'\\\\foo\\bar\\'
, domain:'domain.name'
, username:'username'
, password:'password'
});

smb2Client.readdir('dir_name', function(err, files){
    if(err) throw err;
    console.log(files);
});
```

But it throws the following error, although I am sure my password is correct.

```
Error: STATUS_WRONG_PASSWORD (0xC000006A) : When trying to update a password, this return status indicates that the value provided as the current password is not correct.
    at Object.02000000 (/Users/foo/node_modules/smb2/lib/tools/message.js:25:18)
    at Socket.<anonymous> (/Users/foo/node_modules/smb2/lib/tools/smb2-forge.js:72:31)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)

```

I have implemented the same code using JCIFS library in Java, with the same credentials and it works perfectly.

**Comment by bchelli** [comment]
You have an extra slash at the end of the share:
```javascript
var smb2Client = new SMB2({
  share:'\\\\foo\\bar'
, domain:'domain.name'
, username:'username'
, password:'password'
});
```

Also are you sure that the sharing is properly defined on your windows environment?

Thanks,
