### ISSUE TITLE
STATUS_INVALID_PARAMETER

### ISSUE THREAD

**Issue by gh0st** [bchelli/node-smb2#23]
```typescript
const smb2 = require('smb2');

let smb2Client = new smb2({
  share: '\\\\my-fs\\Projects$',
  domain: 'my.own.domain',
  username: 'myusername',
  password: 'mypassword'
});

smb2Client.readdir('Downloads\\Yankee', (err, files) => {
  if (err) throw  err;
  console.log(files);
});
```

This code alone throws the error:
```
Error: STATUS_INVALID_PARAMETER (0xC000000D) : An invalid parameter was passed to a service or function.
    at Object.04000000 (D:\Developer\simpleProject\node_modules\smb2\lib\tools\message.js:25:18)
    at Socket.<anonymous> (D:\Developer\simpleProject\node_modules\smb2\lib\tools\smb2-forge.js:72:31)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
```

What am I doing wrong?

**Comment by bchelli** [comment]
Can you try with the latest version v0.2.11?

**Comment by gh0st** [comment]
It's been quite a while. I can't remember what I was even using this for. You can close this.

**Comment by bchelli** [comment]
Sorry for the late response @gh0st

**Comment by LeeKevin** [comment]
I'm running 0.2.11 and get the same error. I'm able to connect to the share with Finder on Mac OS and with python's pysmb. No luck with this library though.

**Comment by Jonexuan** [comment]
@LeeKevin Have you solved this problem?
