### ISSUE TITLE
Library cannot run parallel async requests

### ISSUE THREAD

**Issue by aarongodin** [bchelli/node-smb2#25]
I'm using node-smb2 on OSX and have run into an issue where I'm unable to connect due to an EALREADY error being thrown. I was able to connect previously, but after connecting to the same share with the OSX Finder, I've been receiving this error:

```
{ Error: connect EALREADY 10.10.17.83:445 - Local (172.19.0.2:40404)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1106:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
  code: 'EALREADY',
  errno: 'EALREADY',
  syscall: 'connect',
  address: '10.10.17.83',
  port: 445 }
```

## Steps I've taken

The volume has been unmounted from my OSX filesystem. I've removed any references in the Finder to the share. Also, running `smbutil statshares -a` shows an empty table.

I don't believe this is an issue with the node-smb2 but would appreciate any help in troubleshooting. Thanks!

**Comment by aarongodin** [comment]
I have tracked it down to an issue with my code, in addition to an issue with my usage of the library. I am using node's `promisify` to create new versions of the functions on the client prototype, but I believe this library does not allow you to execute two messages in parallel.
