### ISSUE TITLE
logon_faliure if user doesn't have specified domain

### ISSUE THREAD

**Issue by tjswk2008** [bchelli/node-smb2#40]
I can login with any domain or without domain using other linux smb2 client

Error Message: 
```javascript


Error: STATUS_LOGON_FAILURE (0xC000006D) : The attempted logon is invalid. This is either due to a bad username or authentication information.
    at SMB2Forge.request (D:\workspace\webpack-template\node_modules\@marsaud\smb2\lib\tools\smb2-forge.js:22:15)
    at D:\workspace\webpack-template\node_modules\@marsaud\smb2\lib\tools\smb2-connection.js:114:11
    at Object.<anonymous> (D:\workspace\webpack-template\node_modules\@marsaud\smb2\lib\tools\message.js:15:15)
    at Socket.<anonymous> (D:\workspace\webpack-template\node_modules\@marsaud\smb2\lib\tools\smb2-forge.js:71:31)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  messageName: 'session_setup_step2',
  params: {},
  message:
   'STATUS_LOGON_FAILURE (0xC000006D) : The attempted logon is invalid. This is either due to a bad username or authentication information.',
  code: 'STATUS_LOGON_FAILURE'
```

**Comment by mogadanez** [comment]
same issue,  impossible to connect  MAC smb share

**Comment by bwadfort** [comment]
I also have this issue - on a Mac. Looks like the code uses NTLM to authenticate. https://www.npmjs.com/package/ntlm

NTLM authentication challenges require an NT domain, so it looks like this library is relatively coupled to the Windows environment. :(

**Comment by praveen-kukreja** [comment]
Hey @bwadfort @mogadanez , did you find any workaround or other library for connecting to MAC smb share ?
